name: My First Workflow
on: 
  - push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        
      - name: list and read files
        run: |
            echo "A toast to my first Github action ðŸ¥‚"
            ls -ltra
            cat README.md
            
      - name: generate ASCII artwork
        uses: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      # - name: list files
      #   run: ls
        
      # - name: read file
      #   run: cat README.md

