name: My First Workflow
on: 
  - push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "A toast to my first Github action ðŸ¥‚"
        
      - name: list files
        run: ls
        
      - name: read file
        run: cat README.md
