name: My First Workflow
on:
  - push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: List and Read files
        run: |
          echo "A toast to my first Github action ðŸ¥‚"
          ls -ltra
          cat README.md

      # - name: list files
      #   run: ls

      # - name: read file
      #   run: cat README.md
