name: Generate ASCII Artwork
on: 
  - push
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        
      - name: List Repo files
        run: ls -ltra
        
      - name: Executing Shell Script
        run: |
         chmod +x ascii-script.sh
         ./ascii-script.sh
  
  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
      
      - name: Test File Exists
        run: grep -i "dragon" dragon.txt
  
  deploy_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Read File
        run: cat dragon.txt
        
      - name: Deploy
        run: echo "Deploying... .. ."
