# name: Exploring Variable and Secrets
# on:
#   - push
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#   ############ environment variables at STEP level ###############
#       - name: Docker Build
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: owl
#           IMAGE_NAME: github-actions-ngx
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#       - name: Docker Login
#         env:
#           DOCKER_USERNAME: owl
#           DOCKER_PASSWORD: s3cUrePaSsw0rd
#         run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#       - name: Docker Publish
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: owl
#           IMAGE_NAME: github-actions-ngx
#         run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker run
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: owl
#           IMAGE_NAME: github-actions-ngx
#         run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

# name: Exploring Variable and Secrets
# on:
#   - push
# jobs:
#   docker:
#   ############ environment variables at JOBS level ###############
#     env:
#       CONTAINER_REGISTRY: docker.io
#       DOCKER_USERNAME: owl
#       IMAGE_NAME: github-actions-ngx
#       DOCKER_PASSWORD: s3cUrePaSsw0rd
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#       - name: Docker Login
#         run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#       - name: Docker Publish
#         run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#   deploy:
#     env:
#       CONTAINER_REGISTRY: docker.io
#       DOCKER_USERNAME: owl
#       IMAGE_NAME: github-actions-ngx
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker run
#         run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

# name: Exploring Variable and Secrets
# on:
#   - push
#   ############ environment variables at WORKFLOW level ###############
# env:
#   CONTAINER_REGISTRY: docker.io
#   DOCKER_USERNAME: owl
#   IMAGE_NAME: github-actions-ngx
#   DOCKER_PASSWORD: s3cUrePaSsw0rd
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#       - name: Docker Login
#         run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#       - name: Docker Publish
#         run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker run
#         run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

name: Exploring Variable and Secrets
on:
  - push
  ############ environment variables at REPOSITORY level ###############
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-ngx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

      - name: Docker Login
        run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
